// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADqhRqNaRoXzCxSQyRpgyCmh5CwyuxPJY',
    appId: '1:503801609359:web:9ab1993b344b947283c4fa',
    messagingSenderId: '503801609359',
    projectId: 'evently-flutterc15',
    authDomain: 'evently-flutterc15.firebaseapp.com',
    storageBucket: 'evently-flutterc15.firebasestorage.app',
    measurementId: 'G-ZV5ESRMB90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl71hGB_3VIhxWpisqQonz6_18ybzbxu8',
    appId: '1:503801609359:android:20e7d4cfd86231f083c4fa',
    messagingSenderId: '503801609359',
    projectId: 'evently-flutterc15',
    storageBucket: 'evently-flutterc15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0n21mIdhcb1JxDhW4COpe9UpQswfffDM',
    appId: '1:503801609359:ios:c452d8923e6c4be783c4fa',
    messagingSenderId: '503801609359',
    projectId: 'evently-flutterc15',
    storageBucket: 'evently-flutterc15.firebasestorage.app',
    iosClientId: '503801609359-mipcpu5mfbhhihe1lbs19h391gc3uvni.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyC15Flutter',
  );

}